### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pengyiwu** [peter-moran/highway-lane-tracker#4]
Hello peter, for line 538" if str(sys.argv[1]) == 'test':",There is a IndexError。What is the reason？
Thank you so much!

**Comment by peter-moran** [comment]
Presumably you ran the program without any arguments, so `sys.argv[1]` does not exist. 

You are expected/required to pass a video file to the program, which it will then process. Check the readme for the exact usage instructions.

It probably would have been wise to check for cases of no input, but no such checks are done.

**Comment by pengyiwu** [comment]
Thanks, i  am a newbie on Ubuntu. When i ran :python find_lane.py ./data/test_videos/project_video.mp4. 
For the first time ,it succeeded. Then i changed the input video ,ran the above code again, i get a error:not enough valid window to create a fit.  I'm confused.
Thanks so much. 
Have a nice day!
